Bug fixes + improve support on posix (in particular mac port support)
openalea/sconsx pull request #30
Opened 2017-12-15 14:58 UTC by fredboudon

- Add better automatic detection on posix system. 
- Fix problem with similar build and install dirs. 
- Homogeneize libpath variables names.
- Introduce errormsg to report problem.

2017-12-15 15:52 UTC, pradal commented
We need to manage backward compatibility for the tools

2017-12-15 18:22 UTC, fredboudon commented
I did keep backward compatibility. There is still alias name with previous variables.

2018-01-07 11:32 UTC, pradal commented
For Porting to Python 3 the best thing is to open an other Pull Request.
There are different strategies than 2to3 and this has to be discussed.

2018-01-08 17:11 UTC, pradal requested changes

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/bison.py
> +      import openalea.sconsx.errormsg as em
Import this line at the begining of the file

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/eigen.py
> +                import openalea.sconsx.errormsg as em
Import the errormsg module outside the function

2018-01-08 17:11 UTC, pradal commented on src/sconsx/cython.py
> +    from .Cython.Compiler.Main import compile as cython_compile
Cython is not local. It is the global module.
It is not the tool but the real Cython package.

2018-01-08 17:11 UTC, pradal commented on src/sconsx/cython.py
> +        from . import Cython
import Cython rather than .Cython
cython.py is just the sconsx tool not the Cython package

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/eigen.py
> +                import openalea.sconsx.errormsg as em
import the module outside the function.

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/gmp.py
> +          import openalea.sconsx.errormsg as em
Import outside the function

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/install.py
> +        import openalea.sconsx.errormsg as em
This function is a bit of magic. Can you document it and explain.
Please, import also outside the function.

2018-01-08 17:11 UTC, pradal commented on src/sconsx/tools/pthread.py
> +         PathVariable(('pthread_libpath','pthread_lib'), 'pthread libraries path',
How do you manage backport compatibility?

2018-01-11 11:28 UTC, fredboudon commented
All the changes have been fixed

2018-01-11 11:34 UTC, pradal approved these changes

2018-01-11 11:34 UTC, merged